CREATE TABLE IF NOT EXISTS users (
    "Id" SERIAL PRIMARY KEY,
    "Username" VARCHAR(64) NOT NULL,
    "AdminClass" INTEGER NOT NULL DEFAULT 1,
    "IsAdmin" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS reports (
    "Id" SERIAL PRIMARY KEY,
    "UserId" INTEGER NOT NULL,
    "PlayerName" VARCHAR(64) NOT NULL,
    "ViolationType" VARCHAR(64) NOT NULL,
    "Description" VARCHAR(1024) NOT NULL,
    "Priority" INTEGER NOT NULL DEFAULT 1,
    "Status" VARCHAR(32) NOT NULL DEFAULT 'Open',
    "TargetAdminClass" INTEGER NOT NULL DEFAULT 0,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
    "ProcessedAt" TIMESTAMP NULL,
    CONSTRAINT "FK_reports_users" FOREIGN KEY ("UserId") REFERENCES users("Id")
);

CREATE TABLE IF NOT EXISTS app_logs (
    "Id" BIGSERIAL PRIMARY KEY,
    "Level" VARCHAR(16) NOT NULL,
    "Action" VARCHAR(64) NOT NULL,
    "Message" VARCHAR(512) NOT NULL,
    "Details" VARCHAR(2048) NULL,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
);
