CREATE TABLE IF NOT EXISTS users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(64) NOT NULL,
    AdminClass INT NOT NULL DEFAULT 1,
    IsAdmin TINYINT(1) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS reports (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT NOT NULL,
    PlayerName VARCHAR(64) NOT NULL,
    ViolationType VARCHAR(64) NOT NULL,
    Description VARCHAR(1024) NOT NULL,
    Priority INT NOT NULL DEFAULT 1,
    Status VARCHAR(32) NOT NULL DEFAULT 'Open',
    TargetAdminClass INT NOT NULL DEFAULT 0,
    CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ProcessedAt DATETIME NULL,
    CONSTRAINT FK_reports_users FOREIGN KEY (UserId) REFERENCES users(Id)
);
